version: "3.7"
services:

    balancer:
      image: nginx:latest
      container_name: nginx   
      ports:
        - 80:80/tcp
      volumes:
        - /home/vitaliy/devops/docker/nginx/etc:/etc/nginx/conf.d/
      links: 
        - web
        - tomcat

    web:
      build: .
      container_name: apache
      volumes:
        # - /home/vitaliy/devops/docker/web/etc/sites-enabled:/etc/apache2/sites-enabled
        - /home/vitaliy/devops/docker/web/www:/var/www/site
      links:
        - mysql57

    tomcat:
      image: tomcat
      container_name: tomcat
      ports:
        - 8080:8080/tcp
      links:
        - mysql57    

    mysql57:
      image: percona:5.7
      container_name: mysql57
      environment:
        MYSQL_ROOT_PASSWORD: 121212
      # volumes:
      #  - /home/vitaliy/devops/docker/mysql/configs/my.cnf:/etc/mysql/conf.d/custom.cnf
      #  - /home/vitaliy/devops/docker/mysql/mysql:/var/lib/mysql     